import type {
  JamFindOptions,
  JamListResult,
  JamDetailResult,
  MyApplyItem,
  FormedJamFindOptions,
  FormedJamListResult,
  FormedJamDetailResult,
  CreateJamInput,
  CreateApplyInput,
  UpdateJamFormInput,
  EditJamInfoInput,
} from '../../domain/jam/Jam.js';

export interface IJamRepository {
  // ── Queries ─────────────────────────────────────────────────────────────────

  /** GET /allJam — paginated recruitment list */
  findJams(opts: JamFindOptions): Promise<JamListResult>;

  /** GET /singleJam/:juid/:uid? — single recruitment detail */
  findJamByJuid(juid: string, uid?: string): Promise<JamDetailResult>;

  /** GET /getMyApply/:uid — user's apply list */
  findMyApplies(uid: string): Promise<MyApplyItem[] | null>;

  /** GET /allFormedJam — paginated formed band list */
  findFormedJams(opts: FormedJamFindOptions): Promise<FormedJamListResult>;

  /** GET /singleFormedJam/:juid — single formed band detail */
  findFormedJamByJuid(juid: string): Promise<FormedJamDetailResult>;

  // ── Commands ─────────────────────────────────────────────────────────────────

  /** POST /form — create JAM (juid generated by service) */
  createJam(juid: string, data: CreateJamInput): Promise<void>;

  /** POST /apply — apply to join a JAM */
  createApply(data: CreateApplyInput): Promise<void>;

  /** PUT /updateForm — edit recruitment form */
  updateJamForm(juid: string, data: UpdateJamFormInput): Promise<void>;

  /** PUT /joinJam — accept an applicant into the JAM */
  joinJam(
    userId: number,
    userUid: string,
    juid: string,
    applierPlay: number
  ): Promise<'form_success' | 'success'>;

  /** PUT /cancelApply — applicant cancels own apply */
  cancelApply(id: number): Promise<void>;

  /** PUT /deleteApply — former deletes an apply */
  deleteApply(id: number): Promise<void>;

  /** PUT /decideApply — former accepts or rejects an apply */
  decideApply(id: number, state: number): Promise<'cancel' | 'success'>;

  /** PUT /disband — former disbands the JAM */
  disbandJam(juid: string, memberUids: string[]): Promise<void>;

  /** PUT /quit — member quits the JAM */
  quitJam(userId: number, juid: string, playname: string): Promise<void>;

  /** PUT /formRightNow — former forms the band immediately */
  formJamNow(juid: string): Promise<void>;

  /** PUT /editInfo — edit formed band profile */
  editJamInfo(
    juid: string,
    data: EditJamInfoInput,
    coverImg?: string
  ): Promise<void>;
}
